/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.GUI;

import com.esprit.dao.QuestionDAO;
import com.esprit.dao.TestDAO;
import com.esprit.entite.Question;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lenov
 */
public class EcrirTest extends javax.swing.JFrame  {

    /**
     * Creates new form EcrirTest
     */
    
    

    
    public EcrirTest() {
        initComponents();
        TestDAO tdao=new TestDAO();
        nom_test.setText(NomTest.nt);
       
      }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        espace_question = new javax.swing.JTextField();
        num_question = new javax.swing.JLabel();
        ajoutEspaceQuestion = new javax.swing.JButton();
        enregistrer = new javax.swing.JButton();
        categorie = new javax.swing.JTextField();
        nom_test = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        espace_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espace_questionActionPerformed(evt);
            }
        });
        jPanel1.add(espace_question);
        espace_question.setBounds(20, 90, 570, 80);

        num_question.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num_question.setText("Question   :");
        jPanel1.add(num_question);
        num_question.setBounds(40, 50, 90, 40);

        ajoutEspaceQuestion.setText("Ajouter Question");
        ajoutEspaceQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutEspaceQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(ajoutEspaceQuestion);
        ajoutEspaceQuestion.setBounds(130, 200, 170, 23);

        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        jPanel1.add(enregistrer);
        enregistrer.setBounds(370, 200, 170, 23);
        jPanel1.add(categorie);
        categorie.setBounds(599, 90, 120, 80);
        jPanel1.add(nom_test);
        nom_test.setBounds(290, 0, 170, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Categuorie  :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 60, 90, 20);

        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        jPanel1.add(quitter);
        quitter.setBounds(300, 280, 130, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        Question q=new Question();
        q.id_question=0;
        q.id_test=NomTest.idt ;
        q.id_psy=Authentification.idp;
        q.categorie=categorie.getText();
        q.question=espace_question.getText();
        QuestionDAO qdao = new QuestionDAO();
        try {
            qdao.insertQuestion(q);
        } catch (SQLException ex) {
            Logger.getLogger(EcrirTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        close();
        PsySwing ps=new PsySwing();
        ps.setVisible(true);
    }//GEN-LAST:event_enregistrerActionPerformed

    private void ajoutEspaceQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutEspaceQuestionActionPerformed
        Question q=new Question();
        q.id_question=0;
        q.id_test=NomTest.idt ;
        q.id_psy=Authentification.idp;
        q.categorie=categorie.getText();
        q.question=espace_question.getText();
        QuestionDAO qdao = new QuestionDAO();
        try {
            qdao.insertQuestion(q);
        } catch (SQLException ex) {
            Logger.getLogger(EcrirTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        close();
        EcrirTest ecrT=new EcrirTest();
        ecrT.setVisible(true);

    }//GEN-LAST:event_ajoutEspaceQuestionActionPerformed

    private void espace_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espace_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espace_questionActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        close();
    }//GEN-LAST:event_quitterActionPerformed
public void close(){
        WindowEvent winClosingEvent =new WindowEvent(this, WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutEspaceQuestion;
    private javax.swing.JTextField categorie;
    private javax.swing.JButton enregistrer;
    private javax.swing.JTextField espace_question;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nom_test;
    private javax.swing.JLabel num_question;
    private javax.swing.JButton quitter;
    // End of variables declaration//GEN-END:variables
}
