package com.esprit.GUI;


import com.esprit.DAO.PsyDAO;
import com.esprit.entite.Psy;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author imen
 */
public class Inscription_psy_condition extends javax.swing.JFrame {

    /**
     * Creates new form inscription_patient
     */
   
   
    
    public Inscription_psy_condition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        nom = new javax.swing.JLabel();
        ville = new javax.swing.JLabel();
        cin = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jNom = new javax.swing.JTextField();
        jPrenom = new javax.swing.JTextField();
        jCin = new javax.swing.JTextField();
        jAge = new javax.swing.JTextField();
        prenom = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        jTel = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jDiplome = new javax.swing.JTextField();
        diplome = new javax.swing.JLabel();
        jPwd = new javax.swing.JPasswordField();
        pwd = new javax.swing.JLabel();
        jConfPwd = new javax.swing.JPasswordField();
        confpwd = new javax.swing.JLabel();
        jVille = new javax.swing.JTextField();
        jLogin = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        inscrir = new javax.swing.JButton();
        accueil = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nom.setText(" Nom          :");

        ville.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ville.setText("Ville             :");

        cin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cin.setText("Cin             :");

        age.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        age.setText("Age             :");

        jNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomActionPerformed(evt);
            }
        });

        jPrenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrenomActionPerformed(evt);
            }
        });

        jCin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCinActionPerformed(evt);
            }
        });

        jAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgeActionPerformed(evt);
            }
        });

        prenom.setBackground(new java.awt.Color(255, 153, 153));
        prenom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prenom.setText("Prenom      :");

        jEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tel.setText("Tel               :");

        jTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.setText("Email           :");

        jDiplome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDiplome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiplomeActionPerformed(evt);
            }
        });

        diplome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        diplome.setText("Diplome       :");

        pwd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pwd.setText("Password     :");

        confpwd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        confpwd.setText("Confirm pwd :");

        jVille.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVilleActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        login.setText("Login          :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confpwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diplome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLogin)
                    .addComponent(jEmail)
                    .addComponent(jTel)
                    .addComponent(jVille)
                    .addComponent(jConfPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jPwd)
                    .addComponent(jAge)
                    .addComponent(jCin)
                    .addComponent(jPrenom)
                    .addComponent(jNom)
                    .addComponent(jDiplome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLogin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVille, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDiplome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diplome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        inscrir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        inscrir.setText("S'inscrire");
        inscrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrirActionPerformed(evt);
            }
        });

        accueil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        accueil.setText("Accueil");
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Inscription Psychologue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inscrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(inscrir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jNomActionPerformed

    private void jVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVilleActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jVilleActionPerformed

    private void jPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrenomActionPerformed
          // TODO add your handling code here:
    }//GEN-LAST:event_jPrenomActionPerformed

    private void jCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCinActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jCinActionPerformed

    private void jAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgeActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_jAgeActionPerformed

    private void inscrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrirActionPerformed
     PsyDAO pdao=new PsyDAO();
      if(! pdao.findLogin(jLogin.getText())){
     if(! pdao.findPsyByCin(Integer.parseInt(jCin.getText()))){   
       if(! pdao.findPsyByEmail(jEmail.getText())){ 
          if(jPwd.getText().equals(jConfPwd.getText())){ 
              Psy p =new Psy();
              p.setId_psy(0);
              p.setNom_psy(jNom.getText());
              p.setPrenom_psy(jPrenom.getText());
              p.setLogin(jLogin.getText());
              p.setCin_psy(Integer.parseInt(jCin.getText()));
              p.setAge_psy(Integer.parseInt(jAge.getText()));
              p.setPwd_psy(jConfPwd.getText());
              p.setVille(jVille.getText());
              p.setTel_psy(Integer.parseInt(jTel.getText()));
              p.setEmail_psy(jEmail.getText());
              p.setDiplome(jDiplome.getText());
              try {
                  pdao.insertPsy(p);
              } catch (SQLException ex) {
                  System.out.println(ex);
              }
             JOptionPane.showMessageDialog(null,"psy ajouté");
             }else{
              JOptionPane.showMessageDialog(null,"password incorrect");
             }
         }else{
          JOptionPane.showMessageDialog(null,"email existe deja");
         }
     }else{
         JOptionPane.showMessageDialog(null,"cin existe deja");
     }
      }else{
          JOptionPane.showMessageDialog(null,"Login existe deja");
      }
    }//GEN-LAST:event_inscrirActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void jTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelActionPerformed

    private void jDiplomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiplomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDiplomeActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
       Accueil ac =new Accueil();
       ac.setVisible(true);
       close();
    }//GEN-LAST:event_accueilActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    close();
        
    }//GEN-LAST:event_exitActionPerformed
 public void close(){
        WindowEvent winClosingEvent =new WindowEvent(this, WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private javax.swing.JLabel age;
    private javax.swing.JLabel cin;
    private javax.swing.JLabel confpwd;
    private javax.swing.JLabel diplome;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JButton inscrir;
    private javax.swing.JTextField jAge;
    private javax.swing.JTextField jCin;
    private javax.swing.JPasswordField jConfPwd;
    private javax.swing.JTextField jDiplome;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField jLogin;
    private javax.swing.JTextField jNom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPrenom;
    private javax.swing.JPasswordField jPwd;
    private javax.swing.JTextField jTel;
    private javax.swing.JTextField jVille;
    private java.awt.Label label1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel pwd;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel ville;
    // End of variables declaration//GEN-END:variables
}
